### ISSUE TITLE
Do not use input() in library

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/dask-cassandra-loader#1]
The usage of input makes it very hard to test or use it as a dependency.

Please switch to named arguments for functions which use input()

**Comment by romulogoncalves** [comment]
I agree, but at the same time it will make the call of a function super complex. The input was to make it easier when you need to pass a predicate in one of the columns, for example, `shipid in [12, 13, 14]`.

I can get it done, but it will be throwing a lot of exceptions because I need to make sure the query constructed is correct while informing the user where things are going wrong.

**Comment by romulogoncalves** [comment]
The following allows to test code with `input()`.
https://dev.to/vergeev/how-to-test-input-processing-in-python-3

I will remove as much as possible input and then we work on the corner cases.
BTW, to test it how we will need a Cassandra and a Dask cluster, is that right?
Otherwise, the calls do not make sense.

**Comment by romulogoncalves** [comment]
@sverhoeven all code converted and cleanned, now I need to document how the functions should be called. After that we can start creating the tests.

**Comment by romulogoncalves** [comment]
With the commit 421740fee0fc9acfa4a4c1ced4dcd30be67e5732 we have moved away from `input()`.
